name: community_feedback
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  drift: ^2.28.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  font_awesome_flutter: ^10.11.0
  google_fonts: ^6.3.2
  image_cropper: ^11.0.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  lottie: ^3.3.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.40
  toastification: ^3.0.3

dev_dependencies:
  build_runner: ^2.9.0
  drift_dev: ^2.28.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
